#!/usr/bin/env bash
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT"

# shellcheck source=scripts/lib.sh
. "$ROOT/scripts/lib.sh"
load_env

ask() {
  local prompt="$1"
  local default="$2"
  local value
  if ! read -r -p "${prompt} [${default}]: " value; then
    value=""
    echo
  fi
  echo "${value:-$default}"
}

secret() {
  local prompt="$1"
  local default="$2"
  local value
  if ! read -r -s -p "${prompt} [hidden, press enter for default]: " value; then
    value=""
  fi
  echo >&2
  echo "${value:-$default}"
}

echo "Homelab Oneclick setup wizard"
echo
echo "Press enter to accept defaults. You can edit .env later."
echo

TZ_VALUE="$(ask "Timezone" "${TZ:-Asia/Kolkata}")"
PUID_VALUE="$(ask "PUID" "${PUID:-1000}")"
PGID_VALUE="$(ask "PGID" "${PGID:-1000}")"
BIND_IP_VALUE="$(ask "Bind IP (0.0.0.0 for LAN, 127.0.0.1 for local only)" "${BIND_IP:-0.0.0.0}")"

CONFIG_DIR_VALUE="$(ask "Config directory" "${CONFIG_DIR:-./config}")"
DATA_DIR_VALUE="$(ask "Data/cache directory" "${DATA_DIR:-./data}")"
DOWNLOADS_DIR_VALUE="$(ask "Downloads directory" "${DOWNLOADS_DIR:-./downloads}")"
FILES_DIR_VALUE="$(ask "Files directory" "${FILES_DIR:-./files}")"
MEDIA_DIR_VALUE="$(ask "Media directory" "${MEDIA_DIR:-./media-samples}")"
NOTES_DIR_VALUE="$(ask "Notes directory" "${NOTES_DIR:-./notes}")"

WEBDAV_USER_VALUE="$(ask "WebDAV username" "${WEBDAV_USER:-homelab}")"
WEBDAV_PASS_VALUE="$(secret "WebDAV password" "${WEBDAV_PASS:-change-this-webdav-password}")"
HOMEPAGE_ALLOWED_HOSTS_VALUE="$(ask "Homepage allowed hosts" "${HOMEPAGE_ALLOWED_HOSTS:-*}")"
CLOUDFLARE_TUNNEL_TOKEN_VALUE="$(ask "Cloudflare tunnel token (optional)" "${CLOUDFLARE_TUNNEL_TOKEN:-}")"

cat > .env <<ENV
# Generated by ./scripts/setup.sh

TZ=${TZ_VALUE}
PUID=${PUID_VALUE}
PGID=${PGID_VALUE}
HOSTNAME=homelab

CONFIG_DIR=${CONFIG_DIR_VALUE}
DATA_DIR=${DATA_DIR_VALUE}
DOWNLOADS_DIR=${DOWNLOADS_DIR_VALUE}
FILES_DIR=${FILES_DIR_VALUE}
MEDIA_DIR=${MEDIA_DIR_VALUE}
NOTES_DIR=${NOTES_DIR_VALUE}

BIND_IP=${BIND_IP_VALUE}

WEBDAV_USER=${WEBDAV_USER_VALUE}
WEBDAV_PASS=${WEBDAV_PASS_VALUE}

HOMEPAGE_ALLOWED_HOSTS=${HOMEPAGE_ALLOWED_HOSTS_VALUE}
CLOUDFLARE_TUNNEL_TOKEN=${CLOUDFLARE_TUNNEL_TOKEN_VALUE}
ENV

echo
echo "Wrote .env"
echo
if ! read -r -p "Start the core stack now? [Y/n]: " start_now; then
  start_now=""
  echo
fi
if [ "${start_now:-Y}" != "n" ] && [ "${start_now:-Y}" != "N" ]; then
  check_docker_ready
  ./scripts/bootstrap.sh
else
  echo "Run ./scripts/bootstrap.sh when ready."
fi
